import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { cdpCommand, findCdpPage } from "../../core/cdp.js";

type BrowserSession = {
  configured?: boolean;
  cdpPort?: number;
};

type CdpCookie = {
  name?: string;
  value?: string;
  domain?: string;
  path?: string;
  secure?: boolean;
  expires?: number;
};

function clean(value: unknown): string {
  return String(value ?? "").replace(/[\t\r\n]/g, "");
}

function netscapeLine(cookie: CdpCookie): string {
  const domain = clean(cookie.domain);
  return [
    domain,
    domain.startsWith(".") ? "TRUE" : "FALSE",
    clean(cookie.path || "/"),
    cookie.secure ? "TRUE" : "FALSE",
    String(Math.max(0, Math.floor(cookie.expires ?? 0))),
    clean(cookie.name),
    clean(cookie.value)
  ].join("\t");
}

export async function exportBilibiliCdpCookies(appDataRoot: string): Promise<{ cookieFile?: string; warning?: string }> {
  const sessionFile = path.join(process.cwd(), "data", "sessions", "bilibili", "session.json");
  let session: BrowserSession;
  try {
    session = JSON.parse(await readFile(sessionFile, "utf8")) as BrowserSession;
  } catch {
    return { warning: "Bilibili CDP browser session is not configured; BiliSum cookie bridge was skipped." };
  }
  if (!session.configured || !session.cdpPort) return { warning: "Bilibili CDP browser session is not active." };

  const webSocketUrl = await findCdpPage(session.cdpPort, "bilibili.com");
  if (!webSocketUrl) return { warning: `No active Bilibili page found on CDP port ${session.cdpPort}.` };

  const response = await cdpCommand<{ cookies?: CdpCookie[] }>(webSocketUrl, "Network.getAllCookies");
  const cookies = (response.cookies ?? []).filter((cookie) =>
    clean(cookie.domain).includes("bilibili.com") && clean(cookie.name) && clean(cookie.value)
  );
  if (!cookies.some((cookie) => cookie.name === "SESSDATA")) {
    return { warning: "Active Bilibili browser page does not contain a SESSDATA login cookie." };
  }

  const cookieFile = path.join(appDataRoot, "cookies", "bilibili.txt");
  await mkdir(path.dirname(cookieFile), { recursive: true });
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by hotspot-collector from its isolated Bilibili CDP session.",
    ...cookies.sort((a, b) => `${a.domain}${a.path}${a.name}`.localeCompare(`${b.domain}${b.path}${b.name}`)).map(netscapeLine),
    ""
  ];
  await writeFile(cookieFile, lines.join("\n"), "utf8");
  return { cookieFile };
}
